// Dutch–English vocabulary grouped by CEFR level (A1–C1).
// Each entry: nl (Dutch, nouns with de/het article), en (English).
// Rounds draw only from the selected level's list.

const VOCAB_BY_LEVEL = {
  // ══════════════════ A1 · Beginner ══════════════════
  A1: [
    // people & family
    { nl: "de man", en: "man" },
    { nl: "de vrouw", en: "woman" },
    { nl: "het kind", en: "child" },
    { nl: "de jongen", en: "boy" },
    { nl: "het meisje", en: "girl" },
    { nl: "de vader", en: "father" },
    { nl: "de moeder", en: "mother" },
    { nl: "de vriend", en: "friend" },
    { nl: "de familie", en: "family" },
    { nl: "de mensen", en: "people" },
    // home & things
    { nl: "het huis", en: "house" },
    { nl: "de deur", en: "door" },
    { nl: "het raam", en: "window" },
    { nl: "de tafel", en: "table" },
    { nl: "de stoel", en: "chair" },
    { nl: "het bed", en: "bed" },
    { nl: "de keuken", en: "kitchen" },
    { nl: "de kamer", en: "room" },
    { nl: "de tuin", en: "garden" },
    { nl: "de sleutel", en: "key" },
    // places & travel
    { nl: "de straat", en: "street" },
    { nl: "de stad", en: "city" },
    { nl: "het dorp", en: "village" },
    { nl: "het land", en: "country" },
    { nl: "de auto", en: "car" },
    { nl: "de fiets", en: "bicycle" },
    { nl: "de trein", en: "train" },
    { nl: "de bus", en: "bus" },
    { nl: "de winkel", en: "shop" },
    { nl: "de school", en: "school" },
    // food & drink
    { nl: "het water", en: "water" },
    { nl: "het brood", en: "bread" },
    { nl: "de kaas", en: "cheese" },
    { nl: "de melk", en: "milk" },
    { nl: "de koffie", en: "coffee" },
    { nl: "de thee", en: "tea" },
    { nl: "de appel", en: "apple" },
    { nl: "het ei", en: "egg" },
    { nl: "de vis", en: "fish" },
    { nl: "het vlees", en: "meat" },
    // everyday nouns
    { nl: "het geld", en: "money" },
    { nl: "het boek", en: "book" },
    { nl: "de tijd", en: "time" },
    { nl: "de dag", en: "day" },
    { nl: "de week", en: "week" },
    { nl: "de maand", en: "month" },
    { nl: "het jaar", en: "year" },
    { nl: "het uur", en: "hour" },
    { nl: "de ochtend", en: "morning" },
    { nl: "de avond", en: "evening" },
    { nl: "de nacht", en: "night" },
    { nl: "de naam", en: "name" },
    // animals & nature
    { nl: "de hond", en: "dog" },
    { nl: "de kat", en: "cat" },
    { nl: "het weer", en: "weather" },
    { nl: "de zon", en: "sun" },
    { nl: "de regen", en: "rain" },
    { nl: "de sneeuw", en: "snow" },
    // body
    { nl: "de hand", en: "hand" },
    { nl: "het hoofd", en: "head" },
    { nl: "het oog", en: "eye" },
    { nl: "de mond", en: "mouth" },
    // verbs
    { nl: "zijn", en: "to be" },
    { nl: "hebben", en: "to have" },
    { nl: "gaan", en: "to go" },
    { nl: "komen", en: "to come" },
    { nl: "doen", en: "to do" },
    { nl: "maken", en: "to make" },
    { nl: "zien", en: "to see" },
    { nl: "horen", en: "to hear" },
    { nl: "eten", en: "to eat" },
    { nl: "drinken", en: "to drink" },
    { nl: "slapen", en: "to sleep" },
    { nl: "werken", en: "to work" },
    { nl: "wonen", en: "to live, reside" },
    { nl: "spreken", en: "to speak" },
    { nl: "zeggen", en: "to say" },
    { nl: "lezen", en: "to read" },
    { nl: "schrijven", en: "to write" },
    { nl: "lopen", en: "to walk" },
    { nl: "staan", en: "to stand" },
    { nl: "zitten", en: "to sit" },
    { nl: "kopen", en: "to buy" },
    { nl: "geven", en: "to give" },
    { nl: "nemen", en: "to take" },
    { nl: "vinden", en: "to find" },
    { nl: "weten", en: "to know (a fact)" },
    { nl: "leren", en: "to learn" },
    { nl: "spelen", en: "to play" },
    { nl: "wachten", en: "to wait" },
    { nl: "helpen", en: "to help" },
    { nl: "vragen", en: "to ask" },
    { nl: "beginnen", en: "to begin" },
    { nl: "openen", en: "to open" },
    // adjectives
    { nl: "groot", en: "big" },
    { nl: "klein", en: "small" },
    { nl: "goed", en: "good" },
    { nl: "slecht", en: "bad" },
    { nl: "mooi", en: "beautiful" },
    { nl: "oud", en: "old" },
    { nl: "nieuw", en: "new" },
    { nl: "jong", en: "young" },
    { nl: "lang", en: "long, tall" },
    { nl: "kort", en: "short" },
    { nl: "warm", en: "warm" },
    { nl: "koud", en: "cold" },
    { nl: "snel", en: "fast" },
    { nl: "langzaam", en: "slow" },
    { nl: "duur", en: "expensive" },
    { nl: "goedkoop", en: "cheap" },
    { nl: "makkelijk", en: "easy" },
    { nl: "moeilijk", en: "difficult" },
    { nl: "blij", en: "happy, glad" },
    { nl: "ziek", en: "sick" },
    { nl: "vol", en: "full" },
    { nl: "leeg", en: "empty" },
  ],

  // ══════════════════ A2 · Elementary ══════════════════
  A2: [
    // daily life & places
    { nl: "de buurt", en: "neighbourhood" },
    { nl: "de buurman", en: "neighbour" },
    { nl: "de afspraak", en: "appointment, arrangement" },
    { nl: "het weekend", en: "weekend" },
    { nl: "de vakantie", en: "holiday, vacation" },
    { nl: "de reis", en: "trip, journey" },
    { nl: "het vliegtuig", en: "aeroplane" },
    { nl: "het station", en: "station" },
    { nl: "het kaartje", en: "ticket" },
    { nl: "de rekening", en: "bill, account" },
    { nl: "de prijs", en: "price" },
    { nl: "de markt", en: "market" },
    { nl: "het cadeau", en: "gift, present" },
    { nl: "de foto", en: "photo" },
    { nl: "de film", en: "film, movie" },
    { nl: "de muziek", en: "music" },
    { nl: "het feest", en: "party" },
    { nl: "het spel", en: "game" },
    { nl: "de sport", en: "sport" },
    { nl: "het strand", en: "beach" },
    // work & study
    { nl: "de baan", en: "job" },
    { nl: "het kantoor", en: "office" },
    { nl: "de collega", en: "colleague" },
    { nl: "de klant", en: "customer" },
    { nl: "de chef", en: "boss" },
    // health & body
    { nl: "de dokter", en: "doctor" },
    { nl: "het ziekenhuis", en: "hospital" },
    { nl: "de apotheek", en: "pharmacy" },
    { nl: "de tandarts", en: "dentist" },
    { nl: "het lichaam", en: "body" },
    { nl: "de rug", en: "back" },
    { nl: "de keel", en: "throat" },
    { nl: "de arm", en: "arm" },
    { nl: "het been", en: "leg" },
    { nl: "de voet", en: "foot" },
    // nature
    { nl: "de zee", en: "sea" },
    { nl: "het bos", en: "forest" },
    { nl: "de berg", en: "mountain" },
    { nl: "de rivier", en: "river" },
    { nl: "het dier", en: "animal" },
    { nl: "de vogel", en: "bird" },
    { nl: "de boom", en: "tree" },
    { nl: "de bloem", en: "flower" },
    { nl: "de lucht", en: "sky, air" },
    { nl: "de wind", en: "wind" },
    // abstract-lite
    { nl: "het gevoel", en: "feeling" },
    { nl: "de vraag", en: "question" },
    { nl: "het antwoord", en: "answer" },
    { nl: "het probleem", en: "problem" },
    { nl: "de reden", en: "reason" },
    { nl: "het idee", en: "idea" },
    { nl: "de kleur", en: "colour" },
    { nl: "het geluid", en: "sound" },
    { nl: "de fout", en: "mistake" },
    { nl: "de hulp", en: "help" },
    { nl: "de droom", en: "dream" },
    // verbs
    { nl: "reizen", en: "to travel" },
    { nl: "vertrekken", en: "to depart, leave" },
    { nl: "aankomen", en: "to arrive" },
    { nl: "bestellen", en: "to order" },
    { nl: "betalen", en: "to pay" },
    { nl: "proberen", en: "to try" },
    { nl: "gebruiken", en: "to use" },
    { nl: "veranderen", en: "to change" },
    { nl: "gebeuren", en: "to happen" },
    { nl: "voelen", en: "to feel" },
    { nl: "denken", en: "to think" },
    { nl: "geloven", en: "to believe" },
    { nl: "hopen", en: "to hope" },
    { nl: "vergeten", en: "to forget" },
    { nl: "onthouden", en: "to remember, memorise" },
    { nl: "uitleggen", en: "to explain" },
    { nl: "vertellen", en: "to tell" },
    { nl: "brengen", en: "to bring" },
    { nl: "sturen", en: "to send" },
    { nl: "krijgen", en: "to receive, get" },
    { nl: "verliezen", en: "to lose" },
    { nl: "winnen", en: "to win" },
    { nl: "dragen", en: "to wear, carry" },
    { nl: "koken", en: "to cook" },
    { nl: "wassen", en: "to wash" },
    { nl: "repareren", en: "to repair" },
    { nl: "bouwen", en: "to build" },
    { nl: "reserveren", en: "to reserve, book" },
    { nl: "bellen", en: "to call, phone" },
    { nl: "zwemmen", en: "to swim" },
    { nl: "fietsen", en: "to cycle" },
    { nl: "rijden", en: "to drive, ride" },
    { nl: "vliegen", en: "to fly" },
    { nl: "sluiten", en: "to close" },
    // adjectives
    { nl: "druk", en: "busy" },
    { nl: "rustig", en: "quiet, calm" },
    { nl: "vrij", en: "free" },
    { nl: "vroeg", en: "early" },
    { nl: "laat", en: "late" },
    { nl: "vies", en: "dirty" },
    { nl: "schoon", en: "clean" },
    { nl: "nat", en: "wet" },
    { nl: "droog", en: "dry" },
    { nl: "zwaar", en: "heavy" },
    { nl: "licht", en: "light" },
    { nl: "hoog", en: "high" },
    { nl: "laag", en: "low" },
    { nl: "diep", en: "deep" },
    { nl: "leuk", en: "nice, fun" },
    { nl: "aardig", en: "kind, nice" },
    { nl: "vriendelijk", en: "friendly" },
    { nl: "grappig", en: "funny" },
    { nl: "verdrietig", en: "sad" },
    { nl: "bang", en: "afraid" },
    { nl: "belangrijk", en: "important" },
    { nl: "interessant", en: "interesting" },
    { nl: "saai", en: "boring" },
    { nl: "bekend", en: "well-known" },
    { nl: "gezond", en: "healthy" },
    { nl: "moe", en: "tired" },
    { nl: "boos", en: "angry" },
  ],

  // ══════════════════ B1 · Intermediate ══════════════════
  B1: [
    // nouns
    { nl: "de ervaring", en: "experience" },
    { nl: "de verwachting", en: "expectation" },
    { nl: "de mening", en: "opinion" },
    { nl: "de aandacht", en: "attention" },
    { nl: "de herinnering", en: "memory (of an event)" },
    { nl: "de kennis", en: "knowledge" },
    { nl: "de keuze", en: "choice" },
    { nl: "de kans", en: "chance" },
    { nl: "de gelegenheid", en: "occasion, opportunity" },
    { nl: "het geluk", en: "luck, happiness" },
    { nl: "het verdriet", en: "sadness, grief" },
    { nl: "de angst", en: "fear" },
    { nl: "de rust", en: "rest, calm" },
    { nl: "de moeite", en: "effort, trouble" },
    { nl: "de gewoonte", en: "habit, custom" },
    { nl: "het gedrag", en: "behaviour" },
    { nl: "de hoop", en: "hope" },
    { nl: "de omgeving", en: "surroundings, area" },
    { nl: "het milieu", en: "environment (nature)" },
    { nl: "de gebeurtenis", en: "event, occurrence" },
    { nl: "de invloed", en: "influence" },
    { nl: "het verkeer", en: "traffic" },
    { nl: "de file", en: "traffic jam" },
    { nl: "de richting", en: "direction" },
    { nl: "de afstand", en: "distance" },
    { nl: "de snelheid", en: "speed" },
    { nl: "de behandeling", en: "treatment" },
    { nl: "de griep", en: "flu" },
    { nl: "het medicijn", en: "medicine (drug)" },
    { nl: "de toekomst", en: "future (the)" },
    { nl: "het verleden", en: "the past" },
    { nl: "de geschiedenis", en: "history" },
    { nl: "de opleiding", en: "education, training" },
    { nl: "het gesprek", en: "conversation" },
    { nl: "de betekenis", en: "meaning" },
    { nl: "het onderwerp", en: "subject, topic" },
    { nl: "de waarheid", en: "truth" },
    { nl: "de leugen", en: "lie (untruth)" },
    { nl: "de mogelijkheid", en: "possibility" },
    { nl: "het doel", en: "goal, aim" },
    { nl: "het gevolg", en: "consequence" },
    { nl: "de oorzaak", en: "cause" },
    { nl: "de oplossing", en: "solution" },
    { nl: "het voordeel", en: "advantage" },
    { nl: "het nadeel", en: "disadvantage" },
    { nl: "het verschil", en: "difference" },
    { nl: "het voorbeeld", en: "example" },
    { nl: "de vertaling", en: "translation" },
    { nl: "de werkgever", en: "employer" },
    { nl: "de werknemer", en: "employee" },
    { nl: "de sollicitatie", en: "job application" },
    { nl: "de functie", en: "position, role" },
    { nl: "de taak", en: "task" },
    { nl: "de vergadering", en: "meeting" },
    { nl: "de klacht", en: "complaint" },
    { nl: "de huur", en: "rent" },
    { nl: "de winst", en: "profit" },
    { nl: "de verzekering", en: "insurance" },
    { nl: "de korting", en: "discount" },
    // verbs
    { nl: "bereiken", en: "to reach, attain" },
    { nl: "beslissen", en: "to decide" },
    { nl: "beloven", en: "to promise" },
    { nl: "verwachten", en: "to expect" },
    { nl: "verzamelen", en: "to collect, gather" },
    { nl: "vermijden", en: "to avoid" },
    { nl: "voorkomen", en: "to prevent" },
    { nl: "veroorzaken", en: "to cause" },
    { nl: "ontstaan", en: "to arise, come about" },
    { nl: "ontwikkelen", en: "to develop" },
    { nl: "ontdekken", en: "to discover" },
    { nl: "onderzoeken", en: "to investigate" },
    { nl: "vergelijken", en: "to compare" },
    { nl: "blijken", en: "to turn out, prove to be" },
    { nl: "beweren", en: "to claim, assert" },
    { nl: "toegeven", en: "to admit; give in" },
    { nl: "overtuigen", en: "to convince" },
    { nl: "twijfelen", en: "to doubt" },
    { nl: "overwegen", en: "to consider" },
    { nl: "waarderen", en: "to appreciate" },
    { nl: "verbeteren", en: "to improve" },
    { nl: "toenemen", en: "to increase" },
    { nl: "afnemen", en: "to decrease" },
    { nl: "stijgen", en: "to rise, climb" },
    { nl: "dalen", en: "to fall, drop" },
    { nl: "beperken", en: "to limit, restrict" },
    { nl: "verbieden", en: "to forbid" },
    { nl: "toestaan", en: "to allow, permit" },
    { nl: "aanraden", en: "to recommend, advise" },
    { nl: "voorstellen", en: "to propose; introduce" },
    { nl: "uitnodigen", en: "to invite" },
    { nl: "uitstellen", en: "to postpone" },
    { nl: "doorgaan", en: "to go on, continue" },
    { nl: "opgeven", en: "to give up" },
    { nl: "slagen", en: "to succeed, pass" },
    { nl: "mislukken", en: "to fail, go wrong" },
    { nl: "beseffen", en: "to realise" },
    { nl: "opmerken", en: "to notice, remark" },
    { nl: "verklaren", en: "to explain, declare" },
    { nl: "beschrijven", en: "to describe" },
    { nl: "beschermen", en: "to protect" },
    { nl: "verdedigen", en: "to defend" },
    { nl: "verdwijnen", en: "to disappear" },
    { nl: "verschijnen", en: "to appear" },
    { nl: "meemaken", en: "to experience, go through" },
    { nl: "deelnemen", en: "to participate" },
    { nl: "samenwerken", en: "to cooperate" },
    { nl: "weigeren", en: "to refuse" },
    { nl: "vervangen", en: "to replace" },
    { nl: "herstellen", en: "to repair; recover" },
    { nl: "verdienen", en: "to earn, deserve" },
    { nl: "besteden", en: "to spend (time, money)" },
    { nl: "sparen", en: "to save (money)" },
    { nl: "lenen", en: "to borrow, lend" },
    { nl: "genieten", en: "to enjoy" },
    { nl: "klagen", en: "to complain" },
    { nl: "voorbereiden", en: "to prepare" },
    { nl: "verhuizen", en: "to move house" },
    { nl: "bewaren", en: "to keep, store" },
    { nl: "toevoegen", en: "to add" },
    { nl: "verwijderen", en: "to remove, delete" },
    { nl: "invullen", en: "to fill in (a form)" },
    { nl: "regelen", en: "to arrange, organise" },
    { nl: "aanpassen", en: "to adjust, adapt" },
    // adjectives
    { nl: "eerlijk", en: "honest" },
    { nl: "verantwoordelijk", en: "responsible" },
    { nl: "betrouwbaar", en: "reliable" },
    { nl: "zorgvuldig", en: "careful, thorough" },
    { nl: "ingewikkeld", en: "complicated" },
    { nl: "eenvoudig", en: "simple" },
    { nl: "gemiddeld", en: "average" },
    { nl: "uitstekend", en: "excellent" },
    { nl: "gebruikelijk", en: "usual, customary" },
    { nl: "zeldzaam", en: "rare" },
    { nl: "algemeen", en: "general" },
    { nl: "verrassend", en: "surprising" },
    { nl: "teleurstellend", en: "disappointing" },
    { nl: "ontevreden", en: "dissatisfied" },
    { nl: "bezorgd", en: "worried, concerned" },
    { nl: "opgelucht", en: "relieved" },
    { nl: "beleefd", en: "polite" },
    { nl: "verlegen", en: "shy" },
    { nl: "jaloers", en: "jealous" },
    { nl: "behulpzaam", en: "helpful" },
    { nl: "streng", en: "strict" },
    { nl: "geduldig", en: "patient" },
    { nl: "nuttig", en: "useful" },
    { nl: "noodzakelijk", en: "necessary" },
    { nl: "verplicht", en: "compulsory" },
    { nl: "toevallig", en: "coincidental, by chance" },
    { nl: "plotseling", en: "sudden(ly)" },
    { nl: "tijdelijk", en: "temporary" },
    { nl: "dagelijks", en: "daily" },
    { nl: "beschikbaar", en: "available" },
    { nl: "geschikt", en: "suitable" },
    { nl: "waarschijnlijk", en: "probable, likely" },
    { nl: "volledig", en: "complete, full" },
    { nl: "spannend", en: "exciting" },
    { nl: "verstandig", en: "sensible, wise" },
    { nl: "handig", en: "handy, skilful" },
  ],

  // ══════════════════ B2 · Upper-intermediate ══════════════════
  B2: [
    // society, law, politics
    { nl: "de maatschappij", en: "society" },
    { nl: "de overheid", en: "government, authorities" },
    { nl: "de bevolking", en: "population" },
    { nl: "de burger", en: "citizen" },
    { nl: "de vluchteling", en: "refugee" },
    { nl: "de grens", en: "border, limit" },
    { nl: "de wet", en: "law" },
    { nl: "het recht", en: "right (entitlement)" },
    { nl: "de plicht", en: "duty" },
    { nl: "de vrijheid", en: "freedom" },
    { nl: "de rechtbank", en: "court (of law)" },
    { nl: "de straf", en: "punishment" },
    { nl: "de misdaad", en: "crime" },
    { nl: "de schuld", en: "guilt, debt" },
    { nl: "de getuige", en: "witness" },
    { nl: "de verdachte", en: "suspect (person)" },
    { nl: "het slachtoffer", en: "victim" },
    { nl: "de dader", en: "perpetrator, culprit" },
    { nl: "de verkiezing", en: "election" },
    { nl: "het beleid", en: "policy" },
    { nl: "de maatregel", en: "measure (action taken)" },
    { nl: "de belasting", en: "tax" },
    { nl: "de begroting", en: "budget" },
    { nl: "de toestemming", en: "permission" },
    { nl: "het verbod", en: "ban, prohibition" },
    { nl: "de verplichting", en: "obligation" },
    { nl: "het verdrag", en: "treaty" },
    { nl: "de oorlog", en: "war" },
    { nl: "de vrede", en: "peace" },
    { nl: "het leger", en: "army" },
    { nl: "de strijd", en: "struggle, battle" },
    { nl: "de dreiging", en: "threat" },
    { nl: "de vijand", en: "enemy" },
    // work, money, admin
    { nl: "de onderhandeling", en: "negotiation" },
    { nl: "het akkoord", en: "agreement, deal" },
    { nl: "de vergoeding", en: "compensation, reimbursement" },
    { nl: "de bijdrage", en: "contribution" },
    { nl: "de aanvraag", en: "application (formal)" },
    { nl: "de lening", en: "loan" },
    { nl: "de hypotheek", en: "mortgage" },
    { nl: "de rente", en: "interest (on money)" },
    { nl: "de omzet", en: "turnover, revenue" },
    { nl: "het aandeel", en: "share (stock); part" },
    // knowledge & communication
    { nl: "het onderzoek", en: "research, investigation" },
    { nl: "de ontwikkeling", en: "development" },
    { nl: "de wetenschap", en: "science" },
    { nl: "de uitspraak", en: "statement; pronunciation" },
    { nl: "de samenvatting", en: "summary" },
    { nl: "de toelichting", en: "clarification" },
    { nl: "het bewijs", en: "proof, evidence" },
    { nl: "het gerucht", en: "rumour" },
    { nl: "de voorwaarde", en: "condition, precondition" },
    { nl: "de eis", en: "demand, requirement" },
    { nl: "de aanleiding", en: "immediate cause, occasion" },
    { nl: "het besluit", en: "decision, resolution" },
    { nl: "de overeenkomst", en: "similarity; contract" },
    // environment, health, life events
    { nl: "de vervuiling", en: "pollution" },
    { nl: "de uitstoot", en: "emission(s)" },
    { nl: "de overstroming", en: "flood" },
    { nl: "de ramp", en: "disaster" },
    { nl: "de macht", en: "power (over people)" },
    { nl: "de botsing", en: "collision, crash" },
    { nl: "de verwonding", en: "injury, wound" },
    { nl: "de bijwerking", en: "side effect" },
    { nl: "de zwangerschap", en: "pregnancy" },
    { nl: "het overlijden", en: "death, passing" },
    { nl: "de erfenis", en: "inheritance" },
    { nl: "het huwelijk", en: "marriage" },
    { nl: "de scheiding", en: "divorce, separation" },
    { nl: "de opvoeding", en: "upbringing" },
    { nl: "de voorraad", en: "stock, supply" },
    { nl: "de inbraak", en: "burglary" },
    // verbs
    { nl: "uitvinden", en: "to invent" },
    { nl: "ontkennen", en: "to deny" },
    { nl: "beoordelen", en: "to judge, assess" },
    { nl: "verslechteren", en: "to worsen" },
    { nl: "uitbreiden", en: "to expand" },
    { nl: "verplichten", en: "to oblige" },
    { nl: "afraden", en: "to advise against" },
    { nl: "volhouden", en: "to persevere, keep up" },
    { nl: "benadrukken", en: "to emphasise" },
    { nl: "vermelden", en: "to mention" },
    { nl: "betreffen", en: "to concern" },
    { nl: "bedreigen", en: "to threaten" },
    { nl: "aanvallen", en: "to attack" },
    { nl: "vluchten", en: "to flee" },
    { nl: "plaatsvinden", en: "to take place" },
    { nl: "onderhandelen", en: "to negotiate" },
    { nl: "solliciteren", en: "to apply for a job" },
    { nl: "ontslaan", en: "to dismiss, fire" },
    { nl: "aannemen", en: "to accept, hire; assume" },
    { nl: "eisen", en: "to demand" },
    { nl: "dwingen", en: "to force" },
    { nl: "vermoeden", en: "to suspect, presume" },
    { nl: "schatten", en: "to estimate" },
    { nl: "onderbreken", en: "to interrupt" },
    { nl: "opleveren", en: "to yield, produce" },
    { nl: "verspillen", en: "to waste" },
    { nl: "tegenvallen", en: "to be disappointing" },
    { nl: "meevallen", en: "to be better than expected" },
    { nl: "liegen", en: "to lie (not tell the truth)" },
    { nl: "bedriegen", en: "to deceive, cheat" },
    { nl: "stelen", en: "to steal" },
    { nl: "veroordelen", en: "to convict, condemn" },
    { nl: "vaststellen", en: "to determine, establish" },
    { nl: "aantonen", en: "to demonstrate, show" },
    { nl: "bewijzen", en: "to prove" },
    { nl: "verwarren", en: "to confuse" },
    { nl: "bevestigen", en: "to confirm" },
    { nl: "afwijzen", en: "to reject" },
    { nl: "goedkeuren", en: "to approve" },
    { nl: "vertegenwoordigen", en: "to represent" },
    { nl: "begeleiden", en: "to guide, accompany" },
    { nl: "verlengen", en: "to extend, renew" },
    { nl: "voldoen", en: "to satisfy, meet (requirements)" },
    { nl: "ontbreken", en: "to be missing, lack" },
    { nl: "behalen", en: "to achieve, obtain (a result)" },
    // adjectives
    { nl: "afhankelijk", en: "dependent" },
    { nl: "onafhankelijk", en: "independent" },
    { nl: "rechtvaardig", en: "just, fair" },
    { nl: "schuldig", en: "guilty" },
    { nl: "onschuldig", en: "innocent" },
    { nl: "verdacht", en: "suspicious" },
    { nl: "nauwkeurig", en: "accurate, precise" },
    { nl: "opvallend", en: "striking, noticeable" },
    { nl: "merkwaardig", en: "remarkable, odd" },
    { nl: "uitgeput", en: "exhausted" },
    { nl: "verslaafd", en: "addicted" },
    { nl: "gastvrij", en: "hospitable" },
    { nl: "welvarend", en: "prosperous, wealthy" },
    { nl: "waardevol", en: "valuable" },
    { nl: "waardeloos", en: "worthless" },
    { nl: "overbodig", en: "superfluous, unnecessary" },
    { nl: "vrijwillig", en: "voluntary" },
    { nl: "opzettelijk", en: "deliberate, on purpose" },
    { nl: "geleidelijk", en: "gradual(ly)" },
    { nl: "voorlopig", en: "provisional, for now" },
    { nl: "definitief", en: "final, definitive" },
    { nl: "huidig", en: "current, present-day" },
    { nl: "voormalig", en: "former" },
    { nl: "gemeenschappelijk", en: "shared, communal" },
    { nl: "openbaar", en: "public" },
    { nl: "verborgen", en: "hidden" },
    { nl: "bereikbaar", en: "reachable, accessible" },
    { nl: "vergelijkbaar", en: "comparable" },
    { nl: "onverwacht", en: "unexpected" },
    { nl: "onvermijdelijk", en: "inevitable" },
    { nl: "gedeeltelijk", en: "partial(ly)" },
    { nl: "grondig", en: "thorough" },
    { nl: "oppervlakkig", en: "superficial" },
    { nl: "kwetsbaar", en: "vulnerable" },
    // connectors
    { nl: "eigenlijk", en: "actually" },
    { nl: "blijkbaar", en: "apparently" },
    { nl: "uiteraard", en: "of course, naturally" },
    { nl: "bovendien", en: "moreover, besides" },
    { nl: "vervolgens", en: "subsequently, next" },
    { nl: "uiteindelijk", en: "eventually, in the end" },
    { nl: "inmiddels", en: "meanwhile, by now" },
    { nl: "tegenwoordig", en: "nowadays" },
    { nl: "zelden", en: "seldom, rarely" },
    { nl: "hoewel", en: "although" },
    { nl: "ondanks", en: "despite" },
    { nl: "vanwege", en: "because of" },
    { nl: "volgens", en: "according to" },
  ],

  // ══════════════════ C1 · Advanced ══════════════════
  C1: [
    // abstract nouns
    { nl: "de veronderstelling", en: "assumption, supposition" },
    { nl: "de nuance", en: "nuance" },
    { nl: "de tegenstelling", en: "contrast, opposition" },
    { nl: "de tegenstrijdigheid", en: "contradiction" },
    { nl: "de belemmering", en: "obstacle, impediment" },
    { nl: "de weerstand", en: "resistance" },
    { nl: "de terughoudendheid", en: "restraint, reticence" },
    { nl: "de vooringenomenheid", en: "bias" },
    { nl: "het vooroordeel", en: "prejudice" },
    { nl: "de misvatting", en: "misconception" },
    { nl: "de willekeur", en: "arbitrariness" },
    { nl: "de wisselwerking", en: "interaction, interplay" },
    { nl: "de samenhang", en: "coherence, connection" },
    { nl: "de verhouding", en: "ratio, relationship" },
    { nl: "de tendens", en: "tendency, trend" },
    { nl: "de drijfveer", en: "motive, driving force" },
    { nl: "de grondslag", en: "basis, foundation" },
    { nl: "het uitgangspunt", en: "premise, starting point" },
    { nl: "de kanttekening", en: "caveat, marginal note" },
    { nl: "het vraagstuk", en: "issue, problem" },
    { nl: "de kwestie", en: "matter, issue" },
    { nl: "de discrepantie", en: "discrepancy" },
    { nl: "de nadruk", en: "emphasis, stress" },
    { nl: "de reikwijdte", en: "scope, range" },
    { nl: "de omvang", en: "extent, size" },
    { nl: "de strekking", en: "gist, purport" },
    { nl: "de bevinding", en: "finding" },
    { nl: "het bezwaar", en: "objection" },
    { nl: "de opheldering", en: "clarification" },
    { nl: "de vervreemding", en: "alienation" },
    { nl: "de verwezenlijking", en: "realisation, achievement" },
    { nl: "de teloorgang", en: "decline, demise" },
    // verbs
    { nl: "veronderstellen", en: "to presume, assume" },
    { nl: "impliceren", en: "to imply" },
    { nl: "nuanceren", en: "to nuance, qualify" },
    { nl: "belemmeren", en: "to hinder, impede" },
    { nl: "bemoeilijken", en: "to complicate, hamper" },
    { nl: "bewerkstelligen", en: "to bring about, achieve" },
    { nl: "teweegbrengen", en: "to bring about, cause" },
    { nl: "voortvloeien", en: "to result, ensue" },
    { nl: "ondermijnen", en: "to undermine" },
    { nl: "verhullen", en: "to conceal, mask" },
    { nl: "doorgronden", en: "to fathom, grasp fully" },
    { nl: "weerleggen", en: "to refute, rebut" },
    { nl: "ontkrachten", en: "to invalidate, disprove" },
    { nl: "staven", en: "to substantiate, back up" },
    { nl: "bekritiseren", en: "to criticise" },
    { nl: "verwaarlozen", en: "to neglect" },
    { nl: "inwilligen", en: "to grant (a request)" },
    { nl: "afbakenen", en: "to demarcate, define" },
    { nl: "toespitsen", en: "to focus, narrow down" },
    { nl: "uiteenzetten", en: "to set out, expound" },
    { nl: "relativeren", en: "to put into perspective" },
    { nl: "bijstellen", en: "to adjust, revise" },
    { nl: "inschatten", en: "to assess, estimate" },
    { nl: "doorvoeren", en: "to implement, carry through" },
    { nl: "waarborgen", en: "to guarantee, safeguard" },
    { nl: "bekrachtigen", en: "to ratify, affirm" },
    { nl: "afdwingen", en: "to enforce, compel" },
    { nl: "inperken", en: "to curtail, restrict" },
    { nl: "benaderen", en: "to approach; approximate" },
    { nl: "toejuichen", en: "to applaud, welcome" },
    // adjectives
    { nl: "ingrijpend", en: "drastic, far-reaching" },
    { nl: "veelomvattend", en: "comprehensive, wide-ranging" },
    { nl: "ontegenzeglijk", en: "undeniable" },
    { nl: "onmiskenbaar", en: "unmistakable" },
    { nl: "gegrond", en: "well-founded" },
    { nl: "ongegrond", en: "unfounded, groundless" },
    { nl: "doorslaggevend", en: "decisive" },
    { nl: "toonaangevend", en: "leading, authoritative" },
    { nl: "vergaand", en: "far-reaching" },
    { nl: "moeizaam", en: "laborious, difficult" },
    { nl: "stroef", en: "stiff, awkward" },
    { nl: "wisselvallig", en: "changeable, erratic" },
    { nl: "weloverwogen", en: "well-considered" },
    { nl: "lichtzinnig", en: "frivolous, reckless" },
    { nl: "hardnekkig", en: "persistent, stubborn" },
    { nl: "gezaghebbend", en: "authoritative" },
    { nl: "veelzeggend", en: "telling, significant" },
    { nl: "ogenschijnlijk", en: "seemingly, apparently" },
    { nl: "subtiel", en: "subtle" },
    { nl: "genuanceerd", en: "nuanced" },
    { nl: "dubbelzinnig", en: "ambiguous" },
    { nl: "ondubbelzinnig", en: "unambiguous" },
    { nl: "omslachtig", en: "cumbersome, roundabout" },
    { nl: "summier", en: "cursory, brief" },
    // formal connectors
    { nl: "weliswaar", en: "admittedly" },
    { nl: "immers", en: "after all" },
    { nl: "desondanks", en: "nevertheless" },
    { nl: "daarentegen", en: "on the other hand" },
    { nl: "niettemin", en: "nonetheless" },
    { nl: "evenwel", en: "however" },
    { nl: "derhalve", en: "therefore, hence" },
    { nl: "dientengevolge", en: "consequently" },
    { nl: "teneinde", en: "in order to" },
    { nl: "aldus", en: "thus; according to" },
    { nl: "mits", en: "provided that" },
    { nl: "tenzij", en: "unless" },
    { nl: "naargelang", en: "depending on" },
    { nl: "ten opzichte van", en: "in relation to, compared with" },
    { nl: "met betrekking tot", en: "with regard to" },
    { nl: "door middel van", en: "by means of" },
    { nl: "naar aanleiding van", en: "in response to, following" },
    { nl: "in tegenstelling tot", en: "in contrast to" },
    { nl: "met het oog op", en: "with a view to" },
  ],
};

const LEVELS = ["A1", "A2", "B1", "B2", "C1"];
const LEVEL_INFO = {
  A1: "Beginner",
  A2: "Elementary",
  B1: "Intermediate",
  B2: "Upper-intermediate",
  C1: "Advanced",
};
