// B1-B2 Dutch–English vocabulary
// Each entry: nl (Dutch, nouns with article), en (English)
const VOCAB = [
  // ── Nouns: society, government, law ──
  { nl: "de maatschappij", en: "society" },
  { nl: "de overheid", en: "government, the authorities" },
  { nl: "de gemeenschap", en: "community" },
  { nl: "de bevolking", en: "population" },
  { nl: "de burger", en: "citizen" },
  { nl: "de vluchteling", en: "refugee" },
  { nl: "de buitenlander", en: "foreigner" },
  { nl: "de grens", en: "border, limit" },
  { nl: "de wet", en: "law" },
  { nl: "de regel", en: "rule" },
  { nl: "het recht", en: "right (entitlement)" },
  { nl: "de plicht", en: "duty" },
  { nl: "de vrijheid", en: "freedom" },
  { nl: "de gelijkheid", en: "equality" },
  { nl: "de rechtbank", en: "court (of law)" },
  { nl: "de straf", en: "punishment" },
  { nl: "de misdaad", en: "crime" },
  { nl: "de schuld", en: "guilt, debt" },
  { nl: "de getuige", en: "witness" },
  { nl: "de verdachte", en: "suspect (person)" },
  { nl: "het slachtoffer", en: "victim" },
  { nl: "de dader", en: "perpetrator, culprit" },
  { nl: "de verkiezing", en: "election" },
  { nl: "de stem", en: "voice, vote" },
  { nl: "het beleid", en: "policy" },
  { nl: "de maatregel", en: "measure (action taken)" },
  { nl: "de bezuiniging", en: "budget cut" },
  { nl: "de belasting", en: "tax" },
  { nl: "de begroting", en: "budget" },
  { nl: "de toestemming", en: "permission" },
  { nl: "het verbod", en: "ban, prohibition" },
  { nl: "de verplichting", en: "obligation" },
  { nl: "het verdrag", en: "treaty" },
  { nl: "de oorlog", en: "war" },
  { nl: "de vrede", en: "peace" },
  { nl: "het leger", en: "army" },
  { nl: "de overwinning", en: "victory" },
  { nl: "de nederlaag", en: "defeat" },
  { nl: "de strijd", en: "struggle, battle" },
  { nl: "de dreiging", en: "threat" },
  { nl: "het wapen", en: "weapon" },
  { nl: "de vijand", en: "enemy" },
  { nl: "de bondgenoot", en: "ally" },

  // ── Nouns: work, money, admin ──
  { nl: "de werkgever", en: "employer" },
  { nl: "de werknemer", en: "employee" },
  { nl: "de werkloosheid", en: "unemployment" },
  { nl: "de sollicitatie", en: "job application" },
  { nl: "de vacature", en: "vacancy, job opening" },
  { nl: "het loon", en: "wage(s)" },
  { nl: "de functie", en: "position, role" },
  { nl: "de taak", en: "task" },
  { nl: "de verantwoordelijkheid", en: "responsibility" },
  { nl: "de leidinggevende", en: "manager, supervisor" },
  { nl: "de vergadering", en: "meeting" },
  { nl: "het overleg", en: "consultation, deliberation" },
  { nl: "de onderhandeling", en: "negotiation" },
  { nl: "het akkoord", en: "agreement, deal" },
  { nl: "de klacht", en: "complaint" },
  { nl: "de vergoeding", en: "compensation, reimbursement" },
  { nl: "de bijdrage", en: "contribution" },
  { nl: "de aanvraag", en: "application, request (formal)" },
  { nl: "het formulier", en: "form (document)" },
  { nl: "de handtekening", en: "signature" },
  { nl: "de bijlage", en: "attachment, appendix" },
  { nl: "het bestand", en: "file (computer)" },
  { nl: "de gegevens", en: "data, personal details" },
  { nl: "de lening", en: "loan" },
  { nl: "de hypotheek", en: "mortgage" },
  { nl: "de huur", en: "rent" },
  { nl: "de rente", en: "interest (on money)" },
  { nl: "de winst", en: "profit" },
  { nl: "het verlies", en: "loss" },
  { nl: "de omzet", en: "turnover, revenue" },
  { nl: "het aandeel", en: "share (stock); part" },
  { nl: "de verzekering", en: "insurance" },
  { nl: "de korting", en: "discount" },
  { nl: "de bon", en: "receipt, voucher" },
  { nl: "de schadevergoeding", en: "damages, indemnity" },

  // ── Nouns: mind, feelings, qualities ──
  { nl: "de ervaring", en: "experience" },
  { nl: "de verwachting", en: "expectation" },
  { nl: "de mening", en: "opinion" },
  { nl: "de aandacht", en: "attention" },
  { nl: "de herinnering", en: "memory (of an event)" },
  { nl: "het geheugen", en: "memory (ability to remember)" },
  { nl: "de kennis", en: "knowledge" },
  { nl: "de vaardigheid", en: "skill" },
  { nl: "het vermogen", en: "ability, capacity; fortune" },
  { nl: "de eigenschap", en: "quality, trait" },
  { nl: "het kenmerk", en: "feature, characteristic" },
  { nl: "het vertrouwen", en: "trust, confidence" },
  { nl: "de twijfel", en: "doubt" },
  { nl: "de keuze", en: "choice" },
  { nl: "de kans", en: "chance" },
  { nl: "de gelegenheid", en: "occasion, opportunity" },
  { nl: "het geluk", en: "luck, happiness" },
  { nl: "het verdriet", en: "sadness, grief" },
  { nl: "de angst", en: "fear" },
  { nl: "de woede", en: "anger, rage" },
  { nl: "de verbazing", en: "amazement" },
  { nl: "de teleurstelling", en: "disappointment" },
  { nl: "de spanning", en: "tension, excitement" },
  { nl: "de rust", en: "rest, calm" },
  { nl: "de moeite", en: "effort, trouble" },
  { nl: "de gewoonte", en: "habit, custom" },
  { nl: "het gedrag", en: "behaviour" },
  { nl: "het karakter", en: "character, personality" },
  { nl: "het geweten", en: "conscience" },
  { nl: "de wanhoop", en: "despair" },
  { nl: "de hoop", en: "hope" },
  { nl: "de trots", en: "pride" },
  { nl: "de schaamte", en: "shame, embarrassment" },
  { nl: "de jaloezie", en: "jealousy" },
  { nl: "het medelijden", en: "pity, compassion" },

  // ── Nouns: knowledge, communication ──
  { nl: "het onderzoek", en: "research, investigation" },
  { nl: "de ontwikkeling", en: "development" },
  { nl: "de opleiding", en: "education, training programme" },
  { nl: "de wetenschap", en: "science" },
  { nl: "het gesprek", en: "conversation" },
  { nl: "de uitspraak", en: "pronunciation; statement" },
  { nl: "de betekenis", en: "meaning" },
  { nl: "het onderwerp", en: "subject, topic" },
  { nl: "de inhoud", en: "content(s)" },
  { nl: "de samenvatting", en: "summary" },
  { nl: "de toelichting", en: "explanation, clarification" },
  { nl: "het overzicht", en: "overview" },
  { nl: "het bewijs", en: "proof, evidence" },
  { nl: "de waarheid", en: "truth" },
  { nl: "de leugen", en: "lie (untruth)" },
  { nl: "het gerucht", en: "rumour" },
  { nl: "de mogelijkheid", en: "possibility" },
  { nl: "de werkelijkheid", en: "reality" },
  { nl: "de voorwaarde", en: "condition, precondition" },
  { nl: "de eis", en: "demand, requirement" },
  { nl: "het doel", en: "goal, aim" },
  { nl: "het gevolg", en: "consequence, result" },
  { nl: "de oorzaak", en: "cause" },
  { nl: "de aanleiding", en: "immediate cause, occasion for" },
  { nl: "de oplossing", en: "solution" },
  { nl: "het besluit", en: "decision, resolution" },
  { nl: "het voordeel", en: "advantage" },
  { nl: "het nadeel", en: "disadvantage" },
  { nl: "het verschil", en: "difference" },
  { nl: "de overeenkomst", en: "similarity; contract" },
  { nl: "het voorbeeld", en: "example" },
  { nl: "de vertaling", en: "translation" },
  { nl: "de afkorting", en: "abbreviation" },
  { nl: "het misverstand", en: "misunderstanding" },

  // ── Nouns: environment, health, daily life ──
  { nl: "de omgeving", en: "surroundings, area" },
  { nl: "het milieu", en: "environment (nature)" },
  { nl: "de vervuiling", en: "pollution" },
  { nl: "de uitstoot", en: "emission(s)" },
  { nl: "het afval", en: "waste, rubbish" },
  { nl: "de overstroming", en: "flood" },
  { nl: "de droogte", en: "drought" },
  { nl: "de ramp", en: "disaster" },
  { nl: "de gebeurtenis", en: "event, occurrence" },
  { nl: "de kracht", en: "strength, force" },
  { nl: "de macht", en: "power (over people)" },
  { nl: "de invloed", en: "influence" },
  { nl: "de druk", en: "pressure" },
  { nl: "het verkeer", en: "traffic" },
  { nl: "de file", en: "traffic jam" },
  { nl: "de snelweg", en: "motorway, highway" },
  { nl: "het kruispunt", en: "intersection, crossroads" },
  { nl: "de richting", en: "direction" },
  { nl: "de afstand", en: "distance" },
  { nl: "de snelheid", en: "speed" },
  { nl: "het voertuig", en: "vehicle" },
  { nl: "de botsing", en: "collision, crash" },
  { nl: "de verwonding", en: "injury, wound" },
  { nl: "de behandeling", en: "treatment" },
  { nl: "de ontsteking", en: "inflammation, infection" },
  { nl: "de verkoudheid", en: "cold (illness)" },
  { nl: "de griep", en: "flu" },
  { nl: "de koorts", en: "fever" },
  { nl: "de pijnstiller", en: "painkiller" },
  { nl: "het medicijn", en: "medicine (drug)" },
  { nl: "de bijwerking", en: "side effect" },
  { nl: "de zwangerschap", en: "pregnancy" },
  { nl: "de geboorte", en: "birth" },
  { nl: "het overlijden", en: "death, passing" },
  { nl: "de begrafenis", en: "funeral" },
  { nl: "de erfenis", en: "inheritance" },
  { nl: "het huwelijk", en: "marriage" },
  { nl: "de scheiding", en: "divorce, separation" },
  { nl: "de opvoeding", en: "upbringing" },
  { nl: "de jeugd", en: "youth" },
  { nl: "de volwassene", en: "adult" },
  { nl: "de bejaarde", en: "elderly person" },
  { nl: "de eeuw", en: "century" },
  { nl: "de toekomst", en: "future (the)" },
  { nl: "het verleden", en: "the past" },
  { nl: "de geschiedenis", en: "history" },
  { nl: "de voorraad", en: "stock, supply" },
  { nl: "de inbraak", en: "burglary" },
  { nl: "de brandweer", en: "fire brigade" },
  { nl: "de maat", en: "size, measure" },

  // ── Verbs ──
  { nl: "bereiken", en: "to reach, attain" },
  { nl: "beslissen", en: "to decide" },
  { nl: "beloven", en: "to promise" },
  { nl: "verwachten", en: "to expect" },
  { nl: "verzamelen", en: "to collect, gather" },
  { nl: "vermijden", en: "to avoid" },
  { nl: "voorkomen", en: "to prevent" },
  { nl: "veroorzaken", en: "to cause" },
  { nl: "ontstaan", en: "to arise, come into being" },
  { nl: "ontwikkelen", en: "to develop" },
  { nl: "ontdekken", en: "to discover" },
  { nl: "uitvinden", en: "to invent" },
  { nl: "onderzoeken", en: "to investigate, examine" },
  { nl: "vergelijken", en: "to compare" },
  { nl: "verschillen", en: "to differ" },
  { nl: "blijken", en: "to turn out, prove to be" },
  { nl: "beweren", en: "to claim, assert" },
  { nl: "ontkennen", en: "to deny" },
  { nl: "toegeven", en: "to admit; give in" },
  { nl: "overtuigen", en: "to convince" },
  { nl: "twijfelen", en: "to doubt (verb)" },
  { nl: "overwegen", en: "to consider" },
  { nl: "beoordelen", en: "to judge, assess" },
  { nl: "waarderen", en: "to appreciate" },
  { nl: "verbeteren", en: "to improve" },
  { nl: "verslechteren", en: "to worsen" },
  { nl: "toenemen", en: "to increase" },
  { nl: "afnemen", en: "to decrease" },
  { nl: "stijgen", en: "to rise, climb" },
  { nl: "dalen", en: "to fall, drop" },
  { nl: "krimpen", en: "to shrink" },
  { nl: "uitbreiden", en: "to expand" },
  { nl: "beperken", en: "to limit, restrict" },
  { nl: "verbieden", en: "to forbid" },
  { nl: "toestaan", en: "to allow, permit" },
  { nl: "verplichten", en: "to oblige" },
  { nl: "aanraden", en: "to recommend, advise" },
  { nl: "afraden", en: "to advise against" },
  { nl: "voorstellen", en: "to propose; introduce" },
  { nl: "uitnodigen", en: "to invite" },
  { nl: "uitstellen", en: "to postpone" },
  { nl: "afzeggen", en: "to cancel (an appointment)" },
  { nl: "doorgaan", en: "to go on, go ahead" },
  { nl: "opgeven", en: "to give up" },
  { nl: "volhouden", en: "to persevere, keep up" },
  { nl: "slagen", en: "to succeed, pass (an exam)" },
  { nl: "mislukken", en: "to fail, go wrong" },
  { nl: "zich vergissen", en: "to be mistaken" },
  { nl: "zich herinneren", en: "to remember" },
  { nl: "beseffen", en: "to realize" },
  { nl: "opmerken", en: "to notice, remark" },
  { nl: "verklaren", en: "to explain, declare" },
  { nl: "vertalen", en: "to translate" },
  { nl: "beschrijven", en: "to describe" },
  { nl: "benadrukken", en: "to emphasize" },
  { nl: "vermelden", en: "to mention" },
  { nl: "verwijzen naar", en: "to refer to" },
  { nl: "betreffen", en: "to concern" },
  { nl: "behoren tot", en: "to belong to" },
  { nl: "bestaan uit", en: "to consist of" },
  { nl: "afhangen van", en: "to depend on" },
  { nl: "beschermen", en: "to protect" },
  { nl: "bedreigen", en: "to threaten" },
  { nl: "verdedigen", en: "to defend" },
  { nl: "aanvallen", en: "to attack" },
  { nl: "vluchten", en: "to flee" },
  { nl: "verdwijnen", en: "to disappear" },
  { nl: "verschijnen", en: "to appear" },
  { nl: "plaatsvinden", en: "to take place" },
  { nl: "meemaken", en: "to experience, go through" },
  { nl: "deelnemen aan", en: "to participate in" },
  { nl: "bijdragen aan", en: "to contribute to" },
  { nl: "samenwerken", en: "to cooperate" },
  { nl: "onderhandelen", en: "to negotiate" },
  { nl: "solliciteren", en: "to apply for a job" },
  { nl: "ontslaan", en: "to dismiss, fire" },
  { nl: "aannemen", en: "to accept, hire; assume" },
  { nl: "weigeren", en: "to refuse" },
  { nl: "eisen", en: "to demand" },
  { nl: "verzoeken", en: "to request" },
  { nl: "smeken", en: "to beg" },
  { nl: "dwingen", en: "to force" },
  { nl: "vermoeden", en: "to suspect, presume" },
  { nl: "schatten", en: "to estimate" },
  { nl: "meten", en: "to measure" },
  { nl: "wegen", en: "to weigh" },
  { nl: "vervangen", en: "to replace" },
  { nl: "herstellen", en: "to repair; recover" },
  { nl: "storen", en: "to disturb" },
  { nl: "onderbreken", en: "to interrupt" },
  { nl: "opleveren", en: "to yield, produce" },
  { nl: "verdienen", en: "to earn, deserve" },
  { nl: "besteden", en: "to spend (time, money)" },
  { nl: "verspillen", en: "to waste (verb)" },
  { nl: "sparen", en: "to save (money)" },
  { nl: "lenen", en: "to borrow, lend" },
  { nl: "opvallen", en: "to stand out, be noticeable" },
  { nl: "tegenvallen", en: "to be disappointing" },
  { nl: "meevallen", en: "to turn out better than expected" },
  { nl: "wennen aan", en: "to get used to" },
  { nl: "genieten van", en: "to enjoy" },
  { nl: "klagen", en: "to complain" },
  { nl: "troosten", en: "to comfort, console" },
  { nl: "feliciteren", en: "to congratulate" },
  { nl: "zich verontschuldigen", en: "to apologize" },
  { nl: "beledigen", en: "to insult" },
  { nl: "liegen", en: "to lie (not tell the truth)" },
  { nl: "bedriegen", en: "to deceive, cheat" },
  { nl: "stelen", en: "to steal" },
  { nl: "betrappen", en: "to catch (in the act)" },
  { nl: "straffen", en: "to punish" },
  { nl: "veroordelen", en: "to convict, condemn" },
  { nl: "vaststellen", en: "to determine, establish" },
  { nl: "aantonen", en: "to demonstrate, show" },
  { nl: "bewijzen", en: "to prove" },
  { nl: "afleiden", en: "to distract; deduce" },
  { nl: "verwarren", en: "to confuse" },
  { nl: "verwennen", en: "to spoil, pamper" },
  { nl: "opvoeden", en: "to raise, bring up (children)" },
  { nl: "zich gedragen", en: "to behave" },
  { nl: "behandelen", en: "to treat" },
  { nl: "genezen", en: "to heal, cure" },
  { nl: "lijden", en: "to suffer" },
  { nl: "bevallen", en: "to please; give birth" },
  { nl: "flauwvallen", en: "to faint" },
  { nl: "ademen", en: "to breathe" },
  { nl: "zweten", en: "to sweat" },
  { nl: "trillen", en: "to tremble, shake" },
  { nl: "duwen", en: "to push" },
  { nl: "tillen", en: "to lift" },
  { nl: "slepen", en: "to drag" },
  { nl: "raken", en: "to hit, touch" },
  { nl: "richten", en: "to aim, direct" },
  { nl: "voorbereiden", en: "to prepare" },
  { nl: "verhuizen", en: "to move house" },
  { nl: "inrichten", en: "to furnish, arrange (a space)" },
  { nl: "bewaren", en: "to keep, store" },
  { nl: "weggooien", en: "to throw away" },
  { nl: "verdelen", en: "to divide, distribute" },
  { nl: "toevoegen", en: "to add" },
  { nl: "verwijderen", en: "to remove, delete" },
  { nl: "invullen", en: "to fill in (a form)" },
  { nl: "aanvragen", en: "to apply for (a permit, document)" },
  { nl: "regelen", en: "to arrange, organize" },
  { nl: "uitzoeken", en: "to figure out, sort out" },
  { nl: "opzoeken", en: "to look up; visit" },
  { nl: "opnemen", en: "to record; answer the phone" },
  { nl: "uitzenden", en: "to broadcast" },
  { nl: "verspreiden", en: "to spread" },
  { nl: "beïnvloeden", en: "to influence (verb)" },
  { nl: "wijzigen", en: "to modify, change (formal)" },
  { nl: "aanpassen", en: "to adjust, adapt" },
  { nl: "afwijken", en: "to deviate" },
  { nl: "voldoen aan", en: "to meet, satisfy (requirements)" },
  { nl: "ontbreken", en: "to be missing, lack" },
  { nl: "beschikken over", en: "to have at one's disposal" },
  { nl: "behalen", en: "to achieve, obtain (a result)" },
  { nl: "verlengen", en: "to extend, renew" },
  { nl: "versnellen", en: "to speed up" },
  { nl: "vertragen", en: "to delay, slow down" },
  { nl: "bevestigen", en: "to confirm" },
  { nl: "afwijzen", en: "to reject" },
  { nl: "goedkeuren", en: "to approve" },
  { nl: "instemmen met", en: "to agree with, consent to" },
  { nl: "vertegenwoordigen", en: "to represent" },
  { nl: "besturen", en: "to govern; steer" },
  { nl: "leiden", en: "to lead" },
  { nl: "begeleiden", en: "to guide, accompany" },
  { nl: "opleiden", en: "to train, educate" },
  { nl: "afstuderen", en: "to graduate" },
  { nl: "zakken", en: "to fail an exam; sink" },
  { nl: "ophouden", en: "to stop, cease" },
  { nl: "neerzetten", en: "to put down" },
  { nl: "vasthouden", en: "to hold on to" },
  { nl: "loslaten", en: "to let go" },
  { nl: "omgaan met", en: "to deal with, handle" },

  // ── Adjectives ──
  { nl: "afhankelijk", en: "dependent" },
  { nl: "onafhankelijk", en: "independent" },
  { nl: "verantwoordelijk", en: "responsible" },
  { nl: "betrouwbaar", en: "reliable, trustworthy" },
  { nl: "eerlijk", en: "honest" },
  { nl: "rechtvaardig", en: "just, fair" },
  { nl: "schuldig", en: "guilty" },
  { nl: "onschuldig", en: "innocent" },
  { nl: "verdacht", en: "suspicious" },
  { nl: "zorgvuldig", en: "careful, thorough" },
  { nl: "slordig", en: "sloppy, careless" },
  { nl: "nauwkeurig", en: "accurate, precise" },
  { nl: "ingewikkeld", en: "complicated" },
  { nl: "eenvoudig", en: "simple" },
  { nl: "gemiddeld", en: "average" },
  { nl: "uitstekend", en: "excellent" },
  { nl: "uitzonderlijk", en: "exceptional" },
  { nl: "gebruikelijk", en: "usual, customary" },
  { nl: "zeldzaam", en: "rare" },
  { nl: "algemeen", en: "general" },
  { nl: "opvallend", en: "striking, noticeable" },
  { nl: "merkwaardig", en: "remarkable, odd" },
  { nl: "verrassend", en: "surprising" },
  { nl: "teleurstellend", en: "disappointing" },
  { nl: "ontevreden", en: "dissatisfied" },
  { nl: "woedend", en: "furious" },
  { nl: "angstig", en: "anxious, fearful" },
  { nl: "bezorgd", en: "worried, concerned" },
  { nl: "opgelucht", en: "relieved" },
  { nl: "opgewonden", en: "excited" },
  { nl: "verveeld", en: "bored" },
  { nl: "vermoeid", en: "weary, fatigued" },
  { nl: "uitgeput", en: "exhausted" },
  { nl: "gewond", en: "injured, wounded" },
  { nl: "zwanger", en: "pregnant" },
  { nl: "verslaafd", en: "addicted" },
  { nl: "nuchter", en: "sober; down-to-earth" },
  { nl: "beleefd", en: "polite" },
  { nl: "brutaal", en: "cheeky, insolent" },
  { nl: "verlegen", en: "shy" },
  { nl: "zelfverzekerd", en: "self-confident" },
  { nl: "jaloers", en: "jealous" },
  { nl: "gierig", en: "stingy" },
  { nl: "gul", en: "generous" },
  { nl: "behulpzaam", en: "helpful" },
  { nl: "gastvrij", en: "hospitable" },
  { nl: "streng", en: "strict" },
  { nl: "geduldig", en: "patient (adjective)" },
  { nl: "koppig", en: "stubborn" },
  { nl: "ijverig", en: "diligent, hardworking" },
  { nl: "werkloos", en: "unemployed" },
  { nl: "welvarend", en: "prosperous, wealthy" },
  { nl: "kostbaar", en: "precious, costly" },
  { nl: "waardevol", en: "valuable" },
  { nl: "waardeloos", en: "worthless" },
  { nl: "nuttig", en: "useful" },
  { nl: "nutteloos", en: "useless" },
  { nl: "noodzakelijk", en: "necessary" },
  { nl: "overbodig", en: "superfluous, unnecessary" },
  { nl: "verplicht", en: "compulsory, mandatory" },
  { nl: "vrijwillig", en: "voluntary" },
  { nl: "toevallig", en: "coincidental, by chance" },
  { nl: "opzettelijk", en: "deliberate, on purpose" },
  { nl: "geleidelijk", en: "gradual(ly)" },
  { nl: "plotseling", en: "sudden(ly)" },
  { nl: "voorlopig", en: "provisional, for now" },
  { nl: "definitief", en: "final, definitive" },
  { nl: "tijdelijk", en: "temporary" },
  { nl: "blijvend", en: "permanent, lasting" },
  { nl: "huidig", en: "current, present-day" },
  { nl: "voormalig", en: "former" },
  { nl: "toekomstig", en: "future (adjective)" },
  { nl: "aanstaande", en: "upcoming, next" },
  { nl: "dagelijks", en: "daily" },
  { nl: "jaarlijks", en: "annual, yearly" },
  { nl: "gemeenschappelijk", en: "shared, communal" },
  { nl: "openbaar", en: "public" },
  { nl: "particulier", en: "private (non-government)" },
  { nl: "verborgen", en: "hidden" },
  { nl: "zichtbaar", en: "visible" },
  { nl: "beschikbaar", en: "available" },
  { nl: "bereikbaar", en: "reachable, accessible" },
  { nl: "geschikt", en: "suitable" },
  { nl: "vergelijkbaar", en: "comparable" },
  { nl: "tegenovergesteld", en: "opposite" },
  { nl: "onverwacht", en: "unexpected" },
  { nl: "onvermijdelijk", en: "inevitable" },
  { nl: "waarschijnlijk", en: "probable, likely" },
  { nl: "volledig", en: "complete, full" },
  { nl: "gedeeltelijk", en: "partial(ly)" },
  { nl: "afgelegen", en: "remote, isolated" },
  { nl: "spannend", en: "exciting, thrilling" },
  { nl: "saai", en: "boring" },
  { nl: "verstandig", en: "sensible, wise" },
  { nl: "dom", en: "stupid" },
  { nl: "handig", en: "handy, skilful" },
  { nl: "onhandig", en: "clumsy" },
  { nl: "grondig", en: "thorough" },
  { nl: "oppervlakkig", en: "superficial" },
  { nl: "evenwichtig", en: "balanced" },
  { nl: "doorzichtig", en: "transparent" },
  { nl: "stevig", en: "sturdy, firm" },
  { nl: "kwetsbaar", en: "vulnerable" },
  { nl: "scherp", en: "sharp" },
  { nl: "stomp", en: "blunt" },
  { nl: "glad", en: "slippery, smooth" },
  { nl: "ruw", en: "rough" },
  { nl: "vochtig", en: "damp, moist" },
  { nl: "droog", en: "dry" },

  // ── Adverbs, connectors, prepositions ──
  { nl: "nauwelijks", en: "hardly, barely" },
  { nl: "grotendeels", en: "largely, mostly" },
  { nl: "voornamelijk", en: "mainly" },
  { nl: "namelijk", en: "namely; you see" },
  { nl: "eigenlijk", en: "actually" },
  { nl: "blijkbaar", en: "apparently" },
  { nl: "uiteraard", en: "of course, naturally" },
  { nl: "inderdaad", en: "indeed" },
  { nl: "desondanks", en: "nevertheless" },
  { nl: "bovendien", en: "moreover, besides" },
  { nl: "daarentegen", en: "on the other hand" },
  { nl: "vervolgens", en: "subsequently, next" },
  { nl: "aanvankelijk", en: "initially, at first" },
  { nl: "uiteindelijk", en: "eventually, in the end" },
  { nl: "inmiddels", en: "meanwhile, by now" },
  { nl: "onlangs", en: "recently" },
  { nl: "binnenkort", en: "soon, shortly" },
  { nl: "destijds", en: "at the time, back then" },
  { nl: "tegenwoordig", en: "nowadays" },
  { nl: "voortaan", en: "from now on" },
  { nl: "zelden", en: "seldom, rarely" },
  { nl: "telkens", en: "each time, repeatedly" },
  { nl: "overigens", en: "by the way, incidentally" },
  { nl: "weliswaar", en: "admittedly" },
  { nl: "immers", en: "after all" },
  { nl: "hoewel", en: "although" },
  { nl: "tenzij", en: "unless" },
  { nl: "mits", en: "provided that" },
  { nl: "ondanks", en: "despite" },
  { nl: "vanwege", en: "because of" },
  { nl: "volgens", en: "according to" },
  { nl: "ten opzichte van", en: "in relation to, compared with" },
  { nl: "met betrekking tot", en: "with regard to" },
  { nl: "door middel van", en: "by means of" },
  { nl: "naar aanleiding van", en: "in response to, following" },
  { nl: "ten slotte", en: "finally, lastly" },
  { nl: "zowel ... als", en: "both ... and" },
  { nl: "noch ... noch", en: "neither ... nor" },
];
